version: "3"

services:
  app:
    build: ./python
    container_name: python-api
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./python:/app
    depends_on:
      - db
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nomes
    volumes:
      - ./db:/var/lib/postgresql/data
